version: "3.4"
services:
  # PostgreSQL
  postgres:
    container_name: example-com--postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=someuserone
      - POSTGRES_USER=someuser
      - POSTGRES_PASSWORD=YOURPASSWORD
      - REDIS_HOST=redis
    image: postgres:latest
    restart: always
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d/
      - ./postgres/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - example-com--postgres

  # NextCloud
  nextcloud:
    container_name: example-com--nextcloud
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=your_domain_name YOUR_IP
      - OVERWRITEHOST=your_domain_name
      - OVERWRITEPROTOCOL=https
      - OVERWRITECLIURL=https://your_domain_name
    depends_on:
      - postgres
    image: nextcloud:latest
    restart: always
    ports:
      - 1000:80
    volumes:
      - ./nextcloud/html:/var/www/html
      - ./nextcloud/data:/var/www/html/data
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/themes:/var/www/html/themes
      - ./nextcloud/custom_apps:/var/www/html/custom_apps
      - /etc/localtime:/etc/localtime
      - /opt/hooks:/docker-entrypoint-hooks.d
    networks:
      - example-com--postgres
      - example-com--redis

  # Redis
  redis:
    container_name: example-com--redis
    image: redis:latest
    restart: always
    networks:
      - example-com--redis

  cron:
    image: nextcloud:latest
    container_name: example-com--nextcloud-cron
    restart: always
    volumes:
      - ./nextcloud/html:/var/www/html
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/custom_apps:/var/www/html/custom_apps
      - ./nextcloud/data:/var/www/html/data
    entrypoint: /cron.sh
    depends_on:
      - nextcloud
    networks:
      - example-com--postgres
      - example-com--redis

networks:
  example-com--postgres: {}
  example-com--redis: {}
